<a href="https://colab.research.google.com/github/omran35/MSIS822-Project/blob/main/AI_Arabic_Text_Detection_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
from importlib.metadata import version, PackageNotFoundError

packages = ["datasets", "pandas", "numpy", "pyarrow", "notebook", "ipykernel"]

for package in packages:
    try:
        print(f"{package}=={version(package)}")
    except PackageNotFoundError:
        print(f"{package}: not installed in this environment")

datasets==3.1.0
pandas==2.2.3
numpy==2.1.3
pyarrow==23.0.1
notebook==6.5.7
ipykernel==6.17.1

In [13]:
column_types = {}

for name, subset in dataset.items():
    column_types[name] = {
        column: feature.dtype
        for column, feature in subset.features.items()
    }

pd.DataFrame(column_types)

                          by_polishing from_title from_title_and_content
original_abstract               string     string                 string
allam_generated_abstract        string     string                 string
jais_generated_abstract         string     string                 string
llama_generated_abstract        string     string                 string
openai_generated_abstract       string     string                 string

In [12]:
all_data["group_id"] = pd.factorize(human_texts, sort=True)[0]

texts = all_data.melt(
    id_vars=["group_id", "generation_method"],
    value_vars=dataset["by_polishing"].column_names,
    var_name="text_source",
    value_name="text"
)

texts["label"] = (
    texts["text_source"] != "original_abstract"
).astype(int)

counts = texts["label"].value_counts().sort_index()

print("Human (0):", counts[0])
print("AI-generated (1):", counts[1])
print("Total text entries:", len(texts))

Human (0): 8388
AI-generated (1): 33552
Total text entries: 41940

In [11]:
frames = []

for name, subset in dataset.items():
    part = subset.to_pandas()
    part["generation_method"] = name
    frames.append(part)

all_data = pd.concat(frames, ignore_index=True)

human_texts = all_data["original_abstract"].str.strip()

print("Total rows:", len(all_data))
print("Unique human abstracts:", human_texts.nunique())
print("Repeated human entries:", human_texts.duplicated().sum())

Total rows: 8388
Unique human abstracts: 2992
Repeated human entries: 5396

In [10]:
import pandas as pd

checks = []

for name, subset in dataset.items():
    df = subset.to_pandas()

    checks.append({
        "subset": name,
        "rows": len(df),
        "missing_texts": df.isna().sum().sum(),
        "blank_texts": df.apply(
            lambda col: col.dropna().str.strip().eq("").sum()
        ).sum(),
        "duplicate_rows": df.duplicated().sum()
    })

quality_report = pd.DataFrame(checks)
quality_report

                   subset  rows  missing_texts  blank_texts  duplicate_rows
0            by_polishing  2851              0            0               0
1              from_title  2963              0            0               0
2  from_title_and_content  2574              0            0               0

In [9]:
sample = dataset["by_polishing"][0]

print("Human-written abstract:")
print(sample["original_abstract"])

print("\nAI-generated abstract (OpenAI):")
print(sample["openai_generated_abstract"])

Human-written abstract:
كثيرا ما ارتبطت المصادر التاريخية في الأندلس خاصة منها كتب التراجم والفهرسات والبرامج وغيرها بدراسة حياة العلماء والرواة والقضاة والساسة ؛ وقد تطورت هذه المادة حتى ترك لنا المؤلفون الأندلسيون سلسلة متواصلة الحلقات من كتب التـراجم كالصلة لابن بشكوال ، وصلة الصلة لابن الزبير، والتكملة لكتاب الصلة لابن الآبار، والذيل والتكملة لكتابي الموصول والصلة لابن عبد الملك المراكشي إضافة إلى الإحاطة في أخبار غرناطة لابن الخطيب ، إلا أنها لم تنس أن تشير في ثنايا أو بالأحرى في خواتم هذه المؤلفات إلى فئة المرأة العالمة التي ساهمت في الإنتاج الفكري والحضاري الأندلسي. ومن خلالها سنسعى إلى الوقوف على حالة التعليم عند المرأة الأندلسية ، وكيف كانت تأخذ فنون العلم. وما مدى إسهامها في الفكر التربوي والإنتاج الفكري الأندلسيين ؟.

AI-generated abstract (OpenAI):
صور نظام التعليم عند المرأة الأندلسية تستند إلى دراسة دقيقة للمصادر التاريخية التي وثقت حياة العلماء والمثقفين في الأندلس، لا سيما كتب التراجم الشهيرة مثل "الصلة" لابن بشكوال و"صلة الصلة" لابن الزبير و"التكملة" لابن الآبار، وغيرها من الأعمال التي تتابعت لتسجل مراحل تطور البحث العلمي في تلك المنطقة. على الرغم من التركيز الأساسي لهذه المصادر على العلماء الذكور، إلا أن بعضها أشار إلى وجود مجموعة من النساء العالمات اللاتي كن جزءاً من ذلك النشاط الفكري والحضاري. في هذا السياق، يستهدف هذا البحث تحليل دور المرأة الأندلسية في النظام التعليمي، وتحديد الكيفية التي كانت تتلقى بها العلوم والمعارف. بالإضافة إلى ذلك، يهدف إلى تقييم مدى إسهامها في الفكر التربوي والإسهامات الأخرى في المشهد الفكري الأندلسي. يستعرض البحث دور المرأة في المجتمع الأندلسي وكيف أسهمت في النهضة الفكرية من خلال التعلم والمشاركة في الحياة الثقافية، مما يعكس أهمية العلم والتعليم لدى المرأة الأندلسية ومساهمتها الفعالة في بناء التراث التعليمي. توضح الدراسة أن النساء لم يكنَّ مجرد متلقيات للعلوم بل كنَّ أيضاً منتجات ومساهمات في المعرفة، مما يفسح المجال لفهم أكبر لدورهن في إثراء الثقافة الأندلسية.

In [8]:
from datasets import load_dataset

dataset = load_dataset(
    "KFUPM-JRCAI/arabic-generated-abstracts"
)

print(dataset)

DatasetDict({
    by_polishing: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2851
    })
    from_title: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2963
    })
    from_title_and_content: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2574
    })
})

In [7]:
pip install "datasets==3.1.0"

Requirement already satisfied: datasets==3.1.0 in /usr/local/lib/python3.13/dist-packages (3.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (2.1.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (23.0.1)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (4.0.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets==3.1.0) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (3.14.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets==3.1.0) (6.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->datasets==3.1.0) (1.24.5)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->datasets==3.1.0) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->datasets==3.1.0) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->datasets==3.1.0) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->datasets==3.1.0) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets==3.1.0) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets==3.1.0) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets==3.1.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets==3.1.0) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets==3.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets==3.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets==3.1.0) (2026.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->datasets==3.1.0) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->datasets==3.1.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->datasets==3.1.0) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==3.1.0) (1.17.0)