<a href="https://colab.research.google.com/github/omran35/MSIS822-Project/blob/main/AI_Arabic_Text_Detection_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pypdf

Requirement already satisfied: pypdf in /usr/local/lib/python3.13/dist-packages (6.19.0)

In [ ]:
import pypdf

# Open the PDF file
reader = pypdf.PdfReader('/content/Instruction for Final Project MSIS822.pdf')

# Extract and print text to understand the assignment details
full_text = ""
for i, page in enumerate(reader.pages):
    full_text += f"--- Page {i+1} ---\n" + page.extract_text() + "\n"

print("PDF Content Loaded successfully. Length of text:", len(full_text))
# Displaying the first 2000 characters to inspect the structure
print(full_text[:2000])

PDF Content Loaded successfully. Length of text: 18707
--- Page 1 ---


Final Course Graduation Project
MSIS-822 Advanced Data Analytic Techniques

Project Title: Detection of AI-Generated Arabic Text: A Data Mining Approach
Dataset: KFUPM-JRCAI/arabic-generated-abstracts (Available on Hugging Face:
https://huggingface.co/datasets/KFUPM-JRCAI/arabic-generated-abstracts)
1. Overview
1.1 Learning Outcomes
Upon successful completion of this project, the student will be able to:
1. Data Acquisition & Understanding:  Retrieve a dataset from a modern
platform (Hugging Face) and perform an initial exploratory analysis to
understand its structure, balance, and challenges.
2. Data Preprocessing:  Apply and justify specialized text preprocessing
techniques for the Arabic language, including normalization,
stemming/lemmatization, and handling diacritics.
3. Feature Engineering: Transform raw Arabic text into meaningful numerical
features.
4. Modeling & Algorithm Selection: Implement, train, and evaluate a variety of
supervised machine learning methods (deep learning models are optional)
suitable for binary text classification.
5. Model Evaluation & Interpretation:  Critically analyze model performance
using appropriate metrics, perform error analysis, and interpret which features
are most important for the classification decision.
6. Project Lifecycle Management: Demonstrate the ability to manage a complete
data mining project from problem definition to final presentation, including
clear documentation and justification of choices.
1.2 Dataset Description
The dataset addresses the need for comprehensive Arabic machine-generated text
resources, enabling research in detection systems, stylometric analysis, and cross-
model generalization studies.
1.2.1 Dataset Structure
The dataset is organized into different subsets based on generation methods:
Generation Methods
--- Page 2 ---

1. by_polishing - Text refinement approach where models polish existing human
abstracts
2. from_title - Free-form gen

In [ ]:
# Search for Phase 1 details in the PDF content
import re

# Find all occurrences and context around "Phase 1" or "Phase I"
matches = list(re.finditer(r'(?i)phase\s*(?:1|one|i\b)', full_text))
if matches:
    for match in matches:
        start = max(0, match.start() - 200)
        end = min(len(full_text), match.end() + 2000)
        print(f"=== Match found at position {match.start()} ===")
        print(full_text[start:end])
        print("="*50)
else:
    print("Phase 1 keyword not found. Printing full text to inspect structure:")
    print(full_text[:4000])

=== Match found at position 2890 ===
 + paper content
Total 8,388 Across all generation methods

--- Page 3 ---

2. Project Tasks & Timeline
This project is divided into five phases, mimicking a real-world data science workflow.
Phase 1: Project Setup & Data Acquisition ( Deadline: 19
September 2026)
 Task 1.1: Establish a project repository (e.g., on GitHub) to host all code,
reports, and results.
 Task 1.2: Use the datasets library from Hugging Face to download the arabic-
generated-abstracts dataset directly into a Python environment (e.g., Jupyter
Notebook, Google Colab).
 Task 1.3: Perform initial data exploration:
o Load and inspect the dataset structure (columns, data types).
o Check the distribution of the target variable (label: human vs. AI-
generated).
o Assess data quality: check for missing values, duplicates, and
inconsistencies.
Phase 2: Data Preprocessing & Exploratory Data Analysis (EDA)
(Deadline: 21 October 2026)
 Task 2.1: Design and implement an Arabic-specific text preprocessing pipeline.
This should include:
o Normalization (e.g., converting to a standard, removing non-Arabic
characters, handling hamza, alif maqsura).
o Removing diacritics (tashkeel).
o Stop word removal using a standard Arabic stop words list.
o Stemming (using ISRI stemmer) or Lemmatization (if a reliable
lemmatizer is available).
 Task 2.2: Conduct a thorough EDA to find linguistic patterns and differences
between the two classes. This may include:
o Statistical Analysis: Average word length, sentence length, vocabulary
richness (Type-Token Ratio).
o Visualization: Word clouds for each class, frequency distributions of
top n-grams.
o Lexical Analysis: Comparing the use of function words, punctuation,
and specific terms.
--- Page 4 ---

Phase 3: Feature Engineering (Deadline: 30 November 2026)
 Task 3.1: Traditional Features
o Engineer Individual Stylometric Feature Assignment : Each student
will be assigned a specific subset of stylometric features to engineer and
extract from the given text corpus.
How to Determine Your Features:
1. Locate your name on the class roster attached to this document and note your
numerical position, i (where the first name is 𝑖 = 1).
==================================================

In [ ]:
# Search for Phase 1 details in the PDF content
import re

# Find all occurrences and context around "Phase 1" or "Phase I"
matches = re.finditer(r'(?i)phase\s*(?:1|one|i\b)', full_text)
for match in matches:
    start = max(0, match.start() - 200)
    end = min(len(full_text), match.end() + 2000)
    print(f"=== Match found at position {match.start()} ===")
    print(full_text[start:end])
    print("="*50)

=== Match found at position 2890 ===
 + paper content
Total 8,388 Across all generation methods

--- Page 3 ---

2. Project Tasks & Timeline
This project is divided into five phases, mimicking a real-world data science workflow.
Phase 1: Project Setup & Data Acquisition ( Deadline: 19
September 2026)
 Task 1.1: Establish a project repository (e.g., on GitHub) to host all code,
reports, and results.
 Task 1.2: Use the datasets library from Hugging Face to download the arabic-
generated-abstracts dataset directly into a Python environment (e.g., Jupyter
Notebook, Google Colab).
 Task 1.3: Perform initial data exploration:
o Load and inspect the dataset structure (columns, data types).
o Check the distribution of the target variable (label: human vs. AI-
generated).
o Assess data quality: check for missing values, duplicates, and
inconsistencies.
Phase 2: Data Preprocessing & Exploratory Data Analysis (EDA)
(Deadline: 21 October 2026)
 Task 2.1: Design and implement an Arabic-specific text preprocessing pipeline.
This should include:
o Normalization (e.g., converting to a standard, removing non-Arabic
characters, handling hamza, alif maqsura).
o Removing diacritics (tashkeel).
o Stop word removal using a standard Arabic stop words list.
o Stemming (using ISRI stemmer) or Lemmatization (if a reliable
lemmatizer is available).
 Task 2.2: Conduct a thorough EDA to find linguistic patterns and differences
between the two classes. This may include:
o Statistical Analysis: Average word length, sentence length, vocabulary
richness (Type-Token Ratio).
o Visualization: Word clouds for each class, frequency distributions of
top n-grams.
o Lexical Analysis: Comparing the use of function words, punctuation,
and specific terms.
--- Page 4 ---

Phase 3: Feature Engineering (Deadline: 30 November 2026)
 Task 3.1: Traditional Features
o Engineer Individual Stylometric Feature Assignment : Each student
will be assigned a specific subset of stylometric features to engineer and
extract from the given text corpus.
How to Determine Your Features:
1. Locate your name on the class roster attached to this document and note your
numerical position, i (where the first name is 𝑖 = 1).
==================================================

In [ ]:
!pip install datasets pandas

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.5)

In [ ]:
from datasets import load_dataset
import pandas as pd

print("=== Task 1.2: Downloading the dataset from Hugging Face ===")
# Load the dataset
dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

print("Dataset loaded successfully!")
print(dataset)

=== Task 1.2: Downloading the dataset from Hugging Face ===
Dataset loaded successfully!
DatasetDict({
    by_polishing: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2851
    })
    from_title: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2963
    })
    from_title_and_content: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2574
    })
})

In [ ]:
print("=== Task 1.3: Initial Data Exploration ===")

splits = list(dataset.keys())
print(f"Available dataset splits: {splits}\n")

for split in splits:
    df = pd.DataFrame(dataset[split])
    print(f"--- Exploring split: {split} ---")
    print(f"Shape of dataset: {df.shape[0]} rows, {df.shape[1]} columns")
    print("\nColumns and Data Types:")
    print(df.dtypes)

    print("\nFirst 3 rows of the dataset:")
    display(df.head(3))

    # Distribution of the target label
    if 'label' in df.columns:
        print("\nDistribution of the target variable (label):")
        label_counts = df['label'].value_counts()
        label_percentages = df['label'].value_counts(normalize=True) * 100
        for val, cnt in label_counts.items():
            print(f" - Class {val}: {cnt} samples ({label_percentages[val]:.2f}%)")
    else:
        print("\n'label' column not found. Available columns:", df.columns.tolist())

    # Checking for missing values
    print("\nMissing values count per column:")
    print(df.isnull().sum())

    # Checking for duplicates in the text or abstract columns
    text_col = 'text' if 'text' in df.columns else ('abstract' if 'abstract' in df.columns else None)
    if text_col:
        duplicates_count = df.duplicated(subset=[text_col]).sum()
        print(f"\nNumber of duplicate rows based on '{text_col}': {duplicates_count}")
    else:
        duplicates_count = df.duplicated().sum()
        print(f"\nNumber of absolute duplicate rows: {duplicates_count}")

    print("="*60 + "\n")

=== Task 1.3: Initial Data Exploration ===
Available dataset splits: ['by_polishing', 'from_title', 'from_title_and_content']

--- Exploring split: by_polishing ---
Shape of dataset: 2851 rows, 5 columns

Columns and Data Types:
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

First 3 rows of the dataset:

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع التعليم بين النساء الأن...,تدرس هذه الدراسة دور المرأة في التعليم في الأن...,يُقدم هذا البحث دراسة شاملة حول حالة التعليم ع...,صور نظام التعليم عند المرأة الأندلسية تستند إل...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة انهيار دولة الموحدين من...,كان العامل الثقافي من بين الأسباب الرئيسية الت...,يعد العامل الثقافي أحد أبرز الأسباب التي يعزى ...,انهيار دولة الموحدين يعود بشكل كبير للعوامل ال...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,هدفت هذه الدراسة إلى تسليط الضوء على جهود قادة...,تدرس هذه الدراسة جهود قادة الثورة الجزائرية خل...,شكلت الجهود التي بذلها قادة الثورة الجزائرية خ...,جهود قادة الثورة الجزائرية خلال المرحلة الأولى...

'label' column not found. Available columns: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract']

Missing values count per column:
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Number of absolute duplicate rows: 0
============================================================

--- Exploring split: from_title ---
Shape of dataset: 2963 rows, 5 columns

Columns and Data Types:
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

First 3 rows of the dataset:

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يهدف هذا البحث إلى دراسة نظام التعليم عند المر...,تدرس هذه الورقة البحثية نظام التعليم لدى المرأ...,تهدف هذه الورقة البحثية إلى استكشاف صور نظام ا...,البحث يستكشف نظام التعليم عند المرأة الأندلسية...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,تهدف هذه الدراسة إلى تحليل انهيار دولة الموحدي...,تدرس هذه الورقة البحثية انهيار دولة الموحدين، ...,يتناول هذا البحث انهيار دولة الموحدين من خلال ...,تتناول هذه الدراسة البحثية انهيار دولة الموحدي...
2,يقوم المقال على اشكالية الضرائب الغير شرعية في...,تهدف هذه الدراسة إلى استكشاف ظاهرة الضرائب غير...,تدرس هذه الورقة البحثية ظاهرة التهرب الضريبي ف...,يُقدم هذا البحث دراسة تحليلية شاملة للضرائب غي...,تتناول هذه الدراسة البحثية موضوع الضرائب غير ا...

'label' column not found. Available columns: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract']

Missing values count per column:
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Number of absolute duplicate rows: 0
============================================================

--- Exploring split: from_title_and_content ---
Shape of dataset: 2574 rows, 5 columns

Columns and Data Types:
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

First 3 rows of the dataset:

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع نظام التعليم عند المرأة...,تتناول هذه الدراسة نظام التعليم عند المرأة الأ...,تناولت هذه الدراسة نظام التعليم عند المرأة الأ...,يركز البحث على نظام التعليم للمرأة في الأندلس،...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة خلفيات انهيار دولة المو...,يعد العامل الثقافي أحد أبرز الأسباب التي أدت إ...,انهيار دولة الموحدين – دراسة في الخلفيات الثقا...,تناول البحث انهيار دولة الموحدين من منظور خلفي...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,يتناول هذا البحث موضوع تسليح جيش التحرير الوطن...,للأسف، النص المقدم غير واضح وغير قابل للقراءة ...,تسليح جيش التحرير الوطني عبر الحدود الغربية خل...,يبحث هذا البحث في تسليح جيش التحرير الوطني الج...

'label' column not found. Available columns: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract']

Missing values count per column:
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Number of absolute duplicate rows: 0
============================================================

In [ ]:
!pip install datasets pandas

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.29.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.5)

In [ ]:
from datasets import load_dataset
import pandas as pd

print("=== Task 1.2: Downloading the dataset from Hugging Face ===")
# Load the dataset
dataset = load_dataset("KFUPM-JRCAI/arabic-generated-abstracts")

print("Dataset loaded successfully!")
print(dataset)

=== Task 1.2: Downloading the dataset from Hugging Face ===
Dataset loaded successfully!
DatasetDict({
    by_polishing: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2851
    })
    from_title: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2963
    })
    from_title_and_content: Dataset({
        features: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract'],
        num_rows: 2574
    })
})

In [ ]:
print("=== Task 1.3: Initial Data Exploration ===")

# Convert to pandas DataFrame for easier analysis
# Inspect the splits available (usually train/validation/test or just train)
splits = list(dataset.keys())
print(f"Available dataset splits: {splits}\n")

for split in splits:
    df = pd.DataFrame(dataset[split])
    print(f"--- Exploring split: {split} ---")
    print(f"Shape of dataset: {df.shape[0]} rows, {df.shape[1]} columns")
    print("\nColumns and Data Types:")
    print(df.dtypes)

    print("\nFirst 3 rows of the dataset:")
    display(df.head(3))

    # Distribution of the target label
    if 'label' in df.columns:
        print("\nDistribution of the target variable (label):")
        label_counts = df['label'].value_counts()
        label_percentages = df['label'].value_counts(normalize=True) * 100
        for val, cnt in label_counts.items():
            print(f" - Class {val}: {cnt} samples ({label_percentages[val]:.2f}%)")
    else:
        print("\n'label' column not found. Available columns:", df.columns.tolist())

    # Checking for missing values
    print("\nMissing values count per column:")
    print(df.isnull().sum())

    # Checking for duplicates in the text or abstract columns
    text_col = 'text' if 'text' in df.columns else ('abstract' if 'abstract' in df.columns else None)
    if text_col:
        duplicates_count = df.duplicated(subset=[text_col]).sum()
        print(f"\nNumber of duplicate rows based on '{text_col}': {duplicates_count}")
    else:
        duplicates_count = df.duplicated().sum()
        print(f"\nNumber of absolute duplicate rows: {duplicates_count}")

    print("="*60 + "\n")

=== Task 1.3: Initial Data Exploration ===
Available dataset splits: ['by_polishing', 'from_title', 'from_title_and_content']

--- Exploring split: by_polishing ---
Shape of dataset: 2851 rows, 5 columns

Columns and Data Types:
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

First 3 rows of the dataset:

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع التعليم بين النساء الأن...,تدرس هذه الدراسة دور المرأة في التعليم في الأن...,يُقدم هذا البحث دراسة شاملة حول حالة التعليم ع...,صور نظام التعليم عند المرأة الأندلسية تستند إل...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة انهيار دولة الموحدين من...,كان العامل الثقافي من بين الأسباب الرئيسية الت...,يعد العامل الثقافي أحد أبرز الأسباب التي يعزى ...,انهيار دولة الموحدين يعود بشكل كبير للعوامل ال...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,هدفت هذه الدراسة إلى تسليط الضوء على جهود قادة...,تدرس هذه الدراسة جهود قادة الثورة الجزائرية خل...,شكلت الجهود التي بذلها قادة الثورة الجزائرية خ...,جهود قادة الثورة الجزائرية خلال المرحلة الأولى...

'label' column not found. Available columns: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract']

Missing values count per column:
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Number of absolute duplicate rows: 0
============================================================

--- Exploring split: from_title ---
Shape of dataset: 2963 rows, 5 columns

Columns and Data Types:
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

First 3 rows of the dataset:

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يهدف هذا البحث إلى دراسة نظام التعليم عند المر...,تدرس هذه الورقة البحثية نظام التعليم لدى المرأ...,تهدف هذه الورقة البحثية إلى استكشاف صور نظام ا...,البحث يستكشف نظام التعليم عند المرأة الأندلسية...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,تهدف هذه الدراسة إلى تحليل انهيار دولة الموحدي...,تدرس هذه الورقة البحثية انهيار دولة الموحدين، ...,يتناول هذا البحث انهيار دولة الموحدين من خلال ...,تتناول هذه الدراسة البحثية انهيار دولة الموحدي...
2,يقوم المقال على اشكالية الضرائب الغير شرعية في...,تهدف هذه الدراسة إلى استكشاف ظاهرة الضرائب غير...,تدرس هذه الورقة البحثية ظاهرة التهرب الضريبي ف...,يُقدم هذا البحث دراسة تحليلية شاملة للضرائب غي...,تتناول هذه الدراسة البحثية موضوع الضرائب غير ا...

'label' column not found. Available columns: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract']

Missing values count per column:
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Number of absolute duplicate rows: 0
============================================================

--- Exploring split: from_title_and_content ---
Shape of dataset: 2574 rows, 5 columns

Columns and Data Types:
original_abstract            object
allam_generated_abstract     object
jais_generated_abstract      object
llama_generated_abstract     object
openai_generated_abstract    object
dtype: object

First 3 rows of the dataset:

,original_abstract,allam_generated_abstract,jais_generated_abstract,llama_generated_abstract,openai_generated_abstract
0,كثيرا ما ارتبطت المصادر التاريخية في الأندلس خ...,يتناول هذا البحث موضوع نظام التعليم عند المرأة...,تتناول هذه الدراسة نظام التعليم عند المرأة الأ...,تناولت هذه الدراسة نظام التعليم عند المرأة الأ...,يركز البحث على نظام التعليم للمرأة في الأندلس،...
1,يعد العامل الثقافي احد ابرز الاسباب التي يعزى ...,يتناول هذا البحث دراسة خلفيات انهيار دولة المو...,يعد العامل الثقافي أحد أبرز الأسباب التي أدت إ...,انهيار دولة الموحدين – دراسة في الخلفيات الثقا...,تناول البحث انهيار دولة الموحدين من منظور خلفي...
2,شكلت تلك الجهود والمساعي الرائدة التي قام بها ...,يتناول هذا البحث موضوع تسليح جيش التحرير الوطن...,للأسف، النص المقدم غير واضح وغير قابل للقراءة ...,تسليح جيش التحرير الوطني عبر الحدود الغربية خل...,يبحث هذا البحث في تسليح جيش التحرير الوطني الج...

'label' column not found. Available columns: ['original_abstract', 'allam_generated_abstract', 'jais_generated_abstract', 'llama_generated_abstract', 'openai_generated_abstract']

Missing values count per column:
original_abstract            0
allam_generated_abstract     0
jais_generated_abstract      0
llama_generated_abstract     0
openai_generated_abstract    0
dtype: int64

Number of absolute duplicate rows: 0
============================================================